### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by HackerGal** [zignd/HTML-CSS-Class-Completion#327] opened 2021-05-23 20:36 UTC
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

**Comment by zignd** [comment] 2021-08-24 12:49
Duplicate of #155. Also, it is missing the file you were expected to attach.

**Closed as completed by zignd** 2021-08-24 12:49 UTC
