### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 11JoseMarcos11** [zignd/HTML-CSS-Class-Completion#163] opened 2019-02-25 11:08 UTC
Hello. When using the extension in Vscode, the following message appeared:

- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.15.0-45-generic`
- VSCode version: `1.31.1`

Thank you

[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/2900257/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)

**Comment by zignd** [comment] 2019-02-25 11:13
Duplicate of #155

**Closed by zignd** 2019-02-25 11:13 UTC
