### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Anthropoco** [zignd/HTML-CSS-Class-Completion#186] opened 2019-04-15 01:59 UTC
[Zignd.html-css-class-completion-unresponsive.cpuprofile.txt](https://github.com/zignd/HTML-CSS-Class-Completion/files/3078177/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.33.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-04-27 18:51
Duplicate of #155. Also, it is missing the file you were expected to attach.

**Closed by zignd** 2019-04-27 18:51 UTC
