### ISSUE TITLE
"IntelliSense for CSS class names in HTML" extension version 1.20.0 is taking a lot of time whenever I start VS code. It takes like 15min.

### ISSUE THREAD

**Issue by rohan-crypto** [zignd/HTML-CSS-Class-Completion#343] opened 2021-07-12 15:14 UTC
- Issue Type: `Bug`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.20.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.58.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zignd** [comment] 2021-08-24 12:47
Duplicate of #155. Also, it is missing the file you were expected to attach.

**Closed as completed by zignd** 2021-08-24 12:47 UTC
