### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by manuelaraujo1511** [zignd/HTML-CSS-Class-Completion#164] opened 2019-02-27 19:25 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.9.0-8-amd64`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/agonzalez/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-02-27 19:26
Duplicate of #155. Also, missing the report itself.

**Closed by zignd** 2019-02-27 19:26 UTC
