### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by toryangchen** [zignd/HTML-CSS-Class-Completion#204] opened 2019-05-16 02:11 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/01367478/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by wcflmy** [comment] 2019-05-16 10:07
I have the same problem too, but it only appears in my particular projects. When I open that particular project, there is a `Code Helper` which has 100+% cpu. And I finally find out that extension `IntelliSense for CSS class names in HTML` caused this problem. While I uninstall this extension, it will be fine.

**Comment by zignd** [comment] 2019-05-16 12:29
Duplicate of #155. Also, it is missing the file you were expected to attach.

**Closed by zignd** 2019-05-16 12:29 UTC
