### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hossamamen** [zignd/HTML-CSS-Class-Completion#173] opened 2019-03-12 17:11 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hossam/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-03-19 01:43
Duplicate of #155. Also, it's missing the cpuprofile.txt.

**Closed by zignd** 2019-03-19 01:43 UTC
