### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by HendMohammed90** [zignd/HTML-CSS-Class-Completion#165] opened 2019-02-28 07:15 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.20.10-200.fc29.x86_64`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/hendmohammed/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-03-01 13:56
Duplicate of #155. Also, it is missing the file you were warned to attach.

**Closed by zignd** 2019-03-01 13:56 UTC
