### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AnwerShujaFarooqui** [zignd/HTML-CSS-Class-Completion#188] opened 2019-04-17 11:33 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Linux x64 4.15.0-48-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/anwer/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-04-27 18:51
Duplicate of #155. Also, it is missing the file you were expected to attach.

**Closed by zignd** 2019-04-27 18:51 UTC
