### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by 135610177** [zignd/HTML-CSS-Class-Completion#167] opened 2019-03-03 07:49 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\salgam\Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-03-03 17:39
Duplicate of #155. Also missing the file you were expected to attach.

**Closed by zignd** 2019-03-03 17:39 UTC
