### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by skamguia** [zignd/HTML-CSS-Class-Completion#166] opened 2019-02-28 15:14 UTC
- Issue Type: `Performance`
- Extension Name: `html-css-class-completion`
- Extension Version: `1.18.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/skamguia/Zignd.html-css-class-completion-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zignd** [comment] 2019-03-01 13:55
Duplicate of #155. Also, it is missing the file you were warned to attach.

**Closed by zignd** 2019-03-01 13:55 UTC
