### ISSUE TITLE
Remove Markdown "code completion" by default

### ISSUE THREAD

**Issue by j-james** [zignd/HTML-CSS-Class-Completion#162] opened 2019-02-25 01:04 UTC
Every time I press the space bar, [that drop down menu with different Markdown styling options comes up.](https://i.imgur.com/d2zrUwy.png) In my opinion, this is not a good feature to have on by default. It's very intrusive to have pop up every time you finish writing a word. 

Additionally, it's hard to trace back to this extension. I spent the better part of an hour tracking down which one of my extensions was "Markdown Language Basics" (all the information given in the info button). It just to happened to be the second-to-last of my 30-odd extensions that I tested. 

Please consider turning this off by default, or at least putting the name of this extension in the info bubble in the picture I linked.

**Comment by zignd** [comment] 2019-02-25 02:59
The IntelliSense you're looking at can't be provided by this extension as it doesn't support the Markdown file and because it can't look for definitions in files other than CSS files, and they have to be valid CSS files to go through the parser. Even if it was caused by this extension it would show CSS classes instead of Markdown related options.

**Comment by j-james** [comment] 2019-02-25 04:35
I just tested on a separate computer with a clean installation of VS Code, and it did the same thing. No drop down menu in Markdown files before installing. Once the extension is installed, it starts up. 

It's not Intellisense either - it just provides a list of Markdown styles. Clicking them or pressing enter makes it insert into the document. 

I don't know how it's making VS Code do that - maybe overwriting a default setting somewhere? Regardless, it's still happening.

**Comment by zignd** [comment] 2019-02-25 10:34
That's weird, I just checked locally, and it seems that those Markdown suggestions aren't coming from any extension, they are from VS Code itself because I tried CTRL+Space on a VS Code instance with all extensions disabled and the "IntelliSense for CSS class names in HTML" uninstalled and they showed up, then I installed "IntelliSense for CSS class names in HTML" and they were still showing up.

**Comment by j-james** [comment] 2019-02-25 17:54
Hmm. I got different suggestions from pressing CTRL+space than just pressing space (CTRL+space suggests keywords that are used often in the file, space suggests the things in the picture above).

[Here's where the "Markdown Language Basics" is coming from in VS Code.](https://github.com/Microsoft/vscode/tree/4e4e6f9b44dd9e6a53d1f08565c52b8ea9f61a5e/extensions/markdown-basics) I have no clue why the extension is activating it.

**Comment by zignd** [comment] 2019-03-01 13:58
More evidence is needed in order to reproduce the issue. Maybe a screencast would be usefull. Closing for now.

**Closed by zignd** 2019-03-01 13:58 UTC
